# Generated by Django 5.2.8 on 2026-03-09 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reviewreply_reviewvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['-added_at']},
        ),
        migrations.AddField(
            model_name='watchlist',
            name='anime_image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='anime_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='status',
            field=models.CharField(choices=[('W', 'Watching'), ('C', 'Completed'), ('PW', 'Plan to Watch'), ('OH', 'On Hold'), ('D', 'Dropped')], default='PW', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'anime_id')},
        ),
        migrations.AlterModelTable(
            name='watchlist',
            table='watchlist',
        ),
    ]
