# Generated by Django 6.0.2 on 2026-03-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_watchlist_options_watchlist_anime_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='anime_image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='anime_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
